### ISSUE TITLE
Meta boxes are not only for post types

### ISSUE THREAD

**Issue by lkraav** [Automattic/Post-Meta-Inspector#20]
If metaboxes are implement for user editor, https://github.com/Automattic/Post-Meta-Inspector/blob/master/post-meta-inspector.php#L90 assumption will fail.

See https://github.com/stuttter/wp-user-profiles/issues/22#issuecomment-433517170

**Comment by lkraav** [comment]
Hello, does anyone still maintain this plugin?

**Comment by trepmal** [comment]
resolved in #23
